from preprocessing.Preprocessor import Preprocessor
from preprocessing.SinglePreprocessor import SinglePreprocessor
from preprocessing.MultiplePreprocessor import MultiplePreprocessor
from preprocessing.GlobalPreprocessor import GlobalPreprocessor
